# Generated by Django 4.2.1 on 2023-05-15 17:03

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Laptop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("model_name", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("price", models.FloatField()),
            ],
        ),
    ]
