# Generated by Django 4.2.1 on 2023-05-15 17:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="laptop",
            old_name="name",
            new_name="brand",
        ),
    ]
